/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecruiterRegisterRouteImport } from './routes/recruiter-register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppResumeAnalysisRouteImport } from './routes/_app.resume-analysis'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatbotRouteImport } from './routes/_app.chatbot'
import { Route as AppCertificateCheckRouteImport } from './routes/_app.certificate-check'
import { Route as AppApplicationsRouteImport } from './routes/_app.applications'
import { Route as AppRecruiterJobsRouteImport } from './routes/_app.recruiter.jobs'
import { Route as AppRecruiterDashboardRouteImport } from './routes/_app.recruiter.dashboard'
import { Route as AppRecruiterApplicantsRouteImport } from './routes/_app.recruiter.applicants'
import { Route as AppRecruiterAnalyticsRouteImport } from './routes/_app.recruiter.analytics'
import { Route as AppAdminReportsRouteImport } from './routes/_app.admin.reports'
import { Route as AppAdminRecruitersRouteImport } from './routes/_app.admin.recruiters'
import { Route as AppAdminJobsRouteImport } from './routes/_app.admin.jobs'
import { Route as AppAdminDashboardRouteImport } from './routes/_app.admin.dashboard'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app.admin.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRegisterRoute = RecruiterRegisterRouteImport.update({
  id: '/recruiter-register',
  path: '/recruiter-register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppResumeAnalysisRoute = AppResumeAnalysisRouteImport.update({
  id: '/resume-analysis',
  path: '/resume-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatbotRoute = AppChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificateCheckRoute = AppCertificateCheckRouteImport.update({
  id: '/certificate-check',
  path: '/certificate-check',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruiterJobsRoute = AppRecruiterJobsRouteImport.update({
  id: '/recruiter/jobs',
  path: '/recruiter/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruiterDashboardRoute = AppRecruiterDashboardRouteImport.update({
  id: '/recruiter/dashboard',
  path: '/recruiter/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruiterApplicantsRoute = AppRecruiterApplicantsRouteImport.update({
  id: '/recruiter/applicants',
  path: '/recruiter/applicants',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruiterAnalyticsRoute = AppRecruiterAnalyticsRouteImport.update({
  id: '/recruiter/analytics',
  path: '/recruiter/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRecruitersRoute = AppAdminRecruitersRouteImport.update({
  id: '/admin/recruiters',
  path: '/admin/recruiters',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminJobsRoute = AppAdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/recruiter-register': typeof RecruiterRegisterRoute
  '/register': typeof RegisterRoute
  '/applications': typeof AppApplicationsRoute
  '/certificate-check': typeof AppCertificateCheckRoute
  '/chatbot': typeof AppChatbotRoute
  '/dashboard': typeof AppDashboardRoute
  '/jobs': typeof AppJobsRoute
  '/resume-analysis': typeof AppResumeAnalysisRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/jobs': typeof AppAdminJobsRoute
  '/admin/recruiters': typeof AppAdminRecruitersRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/recruiter/analytics': typeof AppRecruiterAnalyticsRoute
  '/recruiter/applicants': typeof AppRecruiterApplicantsRoute
  '/recruiter/dashboard': typeof AppRecruiterDashboardRoute
  '/recruiter/jobs': typeof AppRecruiterJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/recruiter-register': typeof RecruiterRegisterRoute
  '/register': typeof RegisterRoute
  '/applications': typeof AppApplicationsRoute
  '/certificate-check': typeof AppCertificateCheckRoute
  '/chatbot': typeof AppChatbotRoute
  '/dashboard': typeof AppDashboardRoute
  '/jobs': typeof AppJobsRoute
  '/resume-analysis': typeof AppResumeAnalysisRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/jobs': typeof AppAdminJobsRoute
  '/admin/recruiters': typeof AppAdminRecruitersRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/recruiter/analytics': typeof AppRecruiterAnalyticsRoute
  '/recruiter/applicants': typeof AppRecruiterApplicantsRoute
  '/recruiter/dashboard': typeof AppRecruiterDashboardRoute
  '/recruiter/jobs': typeof AppRecruiterJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/recruiter-register': typeof RecruiterRegisterRoute
  '/register': typeof RegisterRoute
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/certificate-check': typeof AppCertificateCheckRoute
  '/_app/chatbot': typeof AppChatbotRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/resume-analysis': typeof AppResumeAnalysisRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/jobs': typeof AppAdminJobsRoute
  '/_app/admin/recruiters': typeof AppAdminRecruitersRoute
  '/_app/admin/reports': typeof AppAdminReportsRoute
  '/_app/recruiter/analytics': typeof AppRecruiterAnalyticsRoute
  '/_app/recruiter/applicants': typeof AppRecruiterApplicantsRoute
  '/_app/recruiter/dashboard': typeof AppRecruiterDashboardRoute
  '/_app/recruiter/jobs': typeof AppRecruiterJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/recruiter-register'
    | '/register'
    | '/applications'
    | '/certificate-check'
    | '/chatbot'
    | '/dashboard'
    | '/jobs'
    | '/resume-analysis'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/jobs'
    | '/admin/recruiters'
    | '/admin/reports'
    | '/recruiter/analytics'
    | '/recruiter/applicants'
    | '/recruiter/dashboard'
    | '/recruiter/jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/recruiter-register'
    | '/register'
    | '/applications'
    | '/certificate-check'
    | '/chatbot'
    | '/dashboard'
    | '/jobs'
    | '/resume-analysis'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/jobs'
    | '/admin/recruiters'
    | '/admin/reports'
    | '/recruiter/analytics'
    | '/recruiter/applicants'
    | '/recruiter/dashboard'
    | '/recruiter/jobs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/contact'
    | '/login'
    | '/recruiter-register'
    | '/register'
    | '/_app/applications'
    | '/_app/certificate-check'
    | '/_app/chatbot'
    | '/_app/dashboard'
    | '/_app/jobs'
    | '/_app/resume-analysis'
    | '/_app/admin/analytics'
    | '/_app/admin/dashboard'
    | '/_app/admin/jobs'
    | '/_app/admin/recruiters'
    | '/_app/admin/reports'
    | '/_app/recruiter/analytics'
    | '/_app/recruiter/applicants'
    | '/_app/recruiter/dashboard'
    | '/_app/recruiter/jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  RecruiterRegisterRoute: typeof RecruiterRegisterRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter-register': {
      id: '/recruiter-register'
      path: '/recruiter-register'
      fullPath: '/recruiter-register'
      preLoaderRoute: typeof RecruiterRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/resume-analysis': {
      id: '/_app/resume-analysis'
      path: '/resume-analysis'
      fullPath: '/resume-analysis'
      preLoaderRoute: typeof AppResumeAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chatbot': {
      id: '/_app/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AppChatbotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certificate-check': {
      id: '/_app/certificate-check'
      path: '/certificate-check'
      fullPath: '/certificate-check'
      preLoaderRoute: typeof AppCertificateCheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruiter/jobs': {
      id: '/_app/recruiter/jobs'
      path: '/recruiter/jobs'
      fullPath: '/recruiter/jobs'
      preLoaderRoute: typeof AppRecruiterJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruiter/dashboard': {
      id: '/_app/recruiter/dashboard'
      path: '/recruiter/dashboard'
      fullPath: '/recruiter/dashboard'
      preLoaderRoute: typeof AppRecruiterDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruiter/applicants': {
      id: '/_app/recruiter/applicants'
      path: '/recruiter/applicants'
      fullPath: '/recruiter/applicants'
      preLoaderRoute: typeof AppRecruiterApplicantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruiter/analytics': {
      id: '/_app/recruiter/analytics'
      path: '/recruiter/analytics'
      fullPath: '/recruiter/analytics'
      preLoaderRoute: typeof AppRecruiterAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/reports': {
      id: '/_app/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/recruiters': {
      id: '/_app/admin/recruiters'
      path: '/admin/recruiters'
      fullPath: '/admin/recruiters'
      preLoaderRoute: typeof AppAdminRecruitersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/jobs': {
      id: '/_app/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AppAdminJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppCertificateCheckRoute: typeof AppCertificateCheckRoute
  AppChatbotRoute: typeof AppChatbotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppJobsRoute: typeof AppJobsRoute
  AppResumeAnalysisRoute: typeof AppResumeAnalysisRoute
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminJobsRoute: typeof AppAdminJobsRoute
  AppAdminRecruitersRoute: typeof AppAdminRecruitersRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppRecruiterAnalyticsRoute: typeof AppRecruiterAnalyticsRoute
  AppRecruiterApplicantsRoute: typeof AppRecruiterApplicantsRoute
  AppRecruiterDashboardRoute: typeof AppRecruiterDashboardRoute
  AppRecruiterJobsRoute: typeof AppRecruiterJobsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRoute,
  AppCertificateCheckRoute: AppCertificateCheckRoute,
  AppChatbotRoute: AppChatbotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppJobsRoute: AppJobsRoute,
  AppResumeAnalysisRoute: AppResumeAnalysisRoute,
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminJobsRoute: AppAdminJobsRoute,
  AppAdminRecruitersRoute: AppAdminRecruitersRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppRecruiterAnalyticsRoute: AppRecruiterAnalyticsRoute,
  AppRecruiterApplicantsRoute: AppRecruiterApplicantsRoute,
  AppRecruiterDashboardRoute: AppRecruiterDashboardRoute,
  AppRecruiterJobsRoute: AppRecruiterJobsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  RecruiterRegisterRoute: RecruiterRegisterRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
